### ISSUE TITLE
「文献」を「作品」に拡張して「アート作品」や「動画」も扱えるようにする

### ISSUE THREAD

**Issue by snize** [ZerobaseInc/genron#34]

**Comment by zerobase** [comment]
- [x] コンテンツタイプ「文献」を「作品」に変更し、扱えるコンテンツの範疇を広げる
- [ ] コンテンツタイプ「文献」のフィールド「文献種別」（単行本、雑誌、記事）を、タクソノミー「作品種別」に変更する

**Comment by zerobase** [comment]
「作品」にあたる Schema.org スキーマは [CreativeWork](https://schema.org/CreativeWork)

**Comment by zerobase** [comment]
- [ ] 作品種別フィールドを追加して、データを入力
- [ ] 文献種別フィールドを削除

**Comment by zerobase** [comment]
- [ ] アート作品とアーティストを追加する
