### ISSUE TITLE
「場所」を導入する

### ISSUE THREAD

**Issue by snize** [ZerobaseInc/genron#36]
イベントや展覧会に

**Comment by zerobase** [comment]
タクソノミーとして実装する。階層構造を表現できる。

**Comment by zerobase** [comment]
Schema.org → https://schema.org/Place

**Comment by zerobase** [comment]
- [ ] 場所タクソノミーを追加する
- [ ] 人物の出身地と、イベントの開催地に場所を入力する
- [ ] イベントのページに場所によるフィルタを追加する
- [ ] 人物のページに場所によるフィルタを追加する
